config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "users#index"
  resources :users,  only: [:index, :new, :create, :edit, :update ,:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  PASSWORD_FORMAT = /\A
    (?=.{8,})          # Must contain 8 or more characters
    (?=.*\d)           # Must contain a digit
    (?=.*[a-z])        # Must contain a lower case character
    (?=.*[A-Z])        # Must contain an upper case character
    (?=.*[[:^alnum:]]) # Must contain a symbol
  /x.freeze

  REGEX_PATTERN = /\A[a-z0-9\+\-_\.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  validates :name, presence: true, uniqueness: true, length: { minimum: 5, maximum: 25 }
  validates :email, presence: true, format: { with: REGEX_PATTERN },
                    uniqueness: true, length: { minimum: 5, maximum: 25 }
  validates :password, presence: true, format: { with: PASSWORD_FORMAT }, length: { minimum: 8, maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'User was successfully created'
      redirect_to new_user_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'User was successfully updated'
      redirect_to users_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BareMetalFormsAndHelpers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <p>
    <%= f.label "Name:" %><br />
    <%= f.text_field :name ,class:"input" %>
  </p>
  <p>
    <%= f.label "Email" %><br />
    <%= f.email_field :email, class:"input" %>
  </p>

  <p>
    <%= f.label "Password" %><br />
    <%= f.password_field :password, class:"input"%>
  </p>

  <p>
    <%= f.submit "Submit", class:"btn-3"%>
  </p>
<% end %>

app/views/users/edit.html.erb
<%= link_to "Home", users_path, class:"home"%>

<div class="container">

<% if @user.errors.any? %>
<h2>The following errors prevented from updating the user:</h2>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>


<h1>Edit user</h1>
<%= render "form" %>

</div>

app/views/users/index.html.erb
<h1 class="heading">Welcome to User generator</h1>

<div class="tablecont">

<h1>All the existing user in the database: <h1>


<%= link_to "+ Create New User", new_user_path, class:"btn"%>

  <table class="table">
    <tr class="thead">
      <th>User Name</th>
      <th>User Email</th>
    </tr>

<% @users.each do |user|%>

<tr style="font-weight:100;">
  <td> <%= user.name %> </td>
  <td> <%= user.email %> </td>
  <td> <%= link_to "Edit", edit_user_path(user), class:"btn-2" %> </td>
  <td> <%= link_to "Show", user_path(user), class:"btn-2" %> </td>
</tr>

<% end %>

  </table>
</div>

app/views/users/new.html.erb
<%= link_to "Home", users_path, class:"home"%>

<div class="container">

<% if @user.errors.any? %>
<h2>The following errors prevented from creating the user:</h2>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>


<h1>Create a new user</h1>

<!-- traditional form
<form action='/users' method='POST' accept-charset="UTF-8">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="username">Username:</label>
    <input type="text" id="username" name="user[name]"><br><br>

    <label for="email">Email:</label>
    <input type="email" id="email" name="user[email]"><br><br>

    <label for="password">Password:</label>
    <input type="password" id="password" name="user[password]"><br><br>

    <input type="submit" value="Submit">

</form>
-->

<%= render "form" %>
</div>

app/views/users/show.html.erb
<%= link_to "Home", users_path, class:"home"%>


<div class="showcont">
<h3>Hello <%= @user.name %>.</h3>
<p>Welcome to our company.</p>
<h3>Your email address is : <%= @user.email %></h3>
</div>